import layerCadastre from './layers/cadastre';
import layerDepartments from './layers/departments';
import layerTownship, {
  townshipInteraction as layerTownshipInteraction,
} from './layers/township';
import layerScot, {
  scotName as layerScotName,
} from './layers/scot';
import layerEpci, {
  epciName as layerEpciName,
  epciInteraction as layerEpciInteraction,
  epciEAELessThan10ha as layerEpciEAELessThan10ha,
  epciEAEAVGSurface as layerEpciEAEAVGSurface,
  epciEAEAVGEmployees as layerEpciEAEAVGEmployees,
  epciEAEEmployees as layerEpciEAEEmployees,
  epciEmploymentDensity as layerEpciEmploymentDensity,
} from './layers/epci';
import layerIndustry from './layers/industry';
import {
  layerEstablishment,
  layersEstablishmentStaticClusters,
  layerEstablishmentColorless,
  layerEstablishmentColorlessStaticClusters,
  layerEstablishmentEmployees,
} from './layers/establishment';
import layerEae, {
  eaeDom as layerEaeDom,
  eaeRegr as layerEaeRegr,
  eaeSurf as layerEaeSurf,
  eaeEmployment as layerEaeEmployment,
  eaeName as layerEaeName,
  eaefoncierDispTheo as layerEaefoncierDispTheo,
  eaefoncierDisp as layerEaefoncierDisp,
  eaeCentroidPoint as layerEaeCentroidPoint,
  eaeGreenActivities as layerEaeGreenActivities,
  eaeIsoVocLogistique5 as layerEaeIsoVocLogistique5,
  eaeIsoVocLogistique10 as layerEaeIsoVocLogistique10,
  eaeIsoVocLogistique15 as layerEaeIsoVocLogistique15,
  eaeIsoVocLogistique20 as layerEaeIsoVocLogistique20,
  eaeIsoVocLogistique25 as layerEaeIsoVocLogistique25,
  eaeIsoVocLogistique30 as layerEaeIsoVocLogistique30,
  eaeLogistique as layerEaeLogistique,
} from './layers/eae';
import
layerTransport, {
  busTransport as layerBusTransport,
  bus as layerBus,
  trainTransport as layerTrainTransport,
  pemTransport as layerPemTransport,
  pemTransportColorless as layerPemTransportColorless,
  train as layerTrains,
  tramTransport as layerTramTransport,
  tram as layerTram,
  taxiTransport as layerTaxiTransport,
  ferryTransport as layerFerryTransport,
  airports as layerAirports,
  roads as layerRoads,
  roadsBis as layerRoadsBis,
  roadTransport as layerRoadTransport,
  roadTransportBis as layerRoadTransportBis,
} from './layers/transport';
import { LayerGareTime15, LayerGareTime30, LayerGareTime45 } from './layers/accessibility';

export default {
  layerCadastre,
  layerDepartments,
  layerTownship,
  layerTownshipInteraction,
  layerScot,
  layerScotName,
  layerTransport,
  layerBusTransport,
  layerBus,
  layerTrainTransport,
  layerPemTransport,
  layerPemTransportColorless,
  layerTramTransport,
  layerTram,
  layerTaxiTransport,
  layerFerryTransport,
  layerEpci,
  layerEpciInteraction,
  layerEpciName,
  layerEae,
  layerEaeDom,
  layerEaeRegr,
  layerEaeSurf,
  layerEpciEAELessThan10ha,
  layerEpciEAEEmployees,
  layerEpciEAEAVGSurface,
  layerEpciEAEAVGEmployees,
  layerEaeEmployment,
  layerEpciEmploymentDensity,
  layerEaeName,
  layerEaeCentroidPoint,
  layerIndustry,
  layerEstablishment,
  layersEstablishmentStaticClusters,
  layerEstablishmentColorless,
  layerEstablishmentColorlessStaticClusters,
  layerAirports,
  layerTrains,
  layerRoads,
  layerRoadsBis,
  layerRoadTransport,
  layerRoadTransportBis,
  layerEaefoncierDispTheo,
  layerEaefoncierDisp,
  layerEaeGreenActivities,
  layerEaeIsoVocLogistique5,
  layerEaeIsoVocLogistique10,
  layerEaeIsoVocLogistique15,
  layerEaeIsoVocLogistique20,
  layerEaeIsoVocLogistique25,
  layerEaeIsoVocLogistique30,
  layerEaeLogistique,
  layerEstablishmentEmployees,
  LayerGareTime15,
  LayerGareTime30,
  LayerGareTime45,
};
